import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";
import AuthProvider from "@/components/common/AuthProvider";
import QueryProvider from "@/providers/QueryProvider";
import FcmProvider from "@/components/common/FcmProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`flex justify-center`}>
        <QueryProvider>
          <AuthProvider>
            <FcmProvider />
            <main className=" relative h-dvh w-93.75">{children}</main>
          </AuthProvider>
          <Toaster />
          <Analytics />
        </QueryProvider>
      </body>
    </html>
  );
}
